name: Build and Publish CLI Release

on:
  push:
    tags:
      - "v*" # Trigger only on version tags like v1.0.0

env:
  PUBLISH_PATH: './dist'
  DOTNET_VERSION: '10.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

permissions:
  contents: write # Required to create releases and upload assets
                # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    # 1. Checkout the repository
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash # For Linux, use bash
      run: |
        pushd './${{ env.PUBLISH_PATH }}'
        dotnet build --configuration Release --output ./output -d diag
        popd

